Updated Brewfile

diff --git a/bin/bak b/bin/bak
--- a/bin/bak
+++ b/bin/bak
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-################### Preparation
+# Cannot be run on Linux
+case "$OSTYPE" in
+    linux*)
+        echo "ERROR: Script does not support Linux!"
+		exit 1
+esac
 
 # echo in case run from shell
 echo "Backup in progress. Please wait..."
diff --git a/bin/dark b/bin/dark
--- a/bin/dark
+++ b/bin/dark
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+# Cannot be run on Linux
+case "$OSTYPE" in
+    linux*)
+        echo "ERROR: Script does not support Linux!"
+		exit 1
+esac
+
 ################################# Get dark mode state
 
 isDarkModeOn=$(
