Fix Marta and VSCode backups to support symlinks

diff --git a/bin/bak b/bin/bak
--- a/bin/bak
+++ b/bin/bak
@@ -2,9 +2,10 @@
 
 # Cannot be run on Linux
 case "$OSTYPE" in
-    linux*)
-        echo "ERROR: Script does not support Linux!"
-		exit 1
+linux*)
+    echo "ERROR: Script does not support Linux!"
+    exit 1
+    ;;
 esac
 
 # echo in case run from shell
@@ -22,20 +23,18 @@ if [[ $(git diff Brewfile) ]]; then
 fi
 
 # Marta
-cp -Rf $HOME/Library/Application\ Support/org.yanex.marta/* $DOTFILES/marta/
 if [[ $(git diff marta) ]]; then
     git add marta/*
     git commit -m "Update Marta settings"
 fi
 
 # VSCode
-cp -Rf $HOME/Library/Application\ Support/Code/User/settings.json $DOTFILES/vscode/
 if [[ $(git diff vscode/settings.json) ]]; then
     git add vscode/settings.json
     git commit -m "Update VSCode settings"
 fi
 
-code --list-extensions | xargs -L 1 echo code --install-extension > $DOTFILES/vscode/extensions.sh
+code --list-extensions | xargs -L 1 echo code --install-extension >$DOTFILES/vscode/extensions.sh
 chmod +x $DOTFILES/vscode/extensions.sh
 if [[ $(git diff vscode/extensions.sh) ]]; then
     git add vscode/extensions.sh
