Minor improvements

diff --git a/bin/imgcat b/bin/imgcat
--- a/bin/imgcat
+++ b/bin/imgcat
@@ -1,11 +1,12 @@
 #!/bin/bash
 
+# by George Nachman https://www.iterm2.com/documentation-images.html
 # tmux requires unrecognized OSC sequences to be wrapped with DCS tmux;
 # <sequence> ST, and for all ESCs in <sequence> to be replaced with ESC ESC. It
 # only accepts ESC backslash for ST. We use TERM instead of TMUX because TERM
 # gets passed through ssh.
 function print_osc() {
-    if [[ $TERM == screen* ]] ; then
+    if [[ $TERM == screen* ]]; then
         printf "\033Ptmux;\033\033]"
     else
         printf "\033]"
@@ -14,7 +15,7 @@ function print_osc() {
 
 # More of the tmux workaround described above.
 function print_st() {
-    if [[ $TERM == screen* ]] ; then
+    if [[ $TERM == screen* ]]; then
         printf "\a\033\\"
     else
         printf "\a"
@@ -40,11 +41,11 @@ function b64_encode() {
 function b64_decode() {
     load_version
     if [[ "$IMGCAT_BASE64_VERSION" =~ fourmilab ]]; then
-      BASE64ARG=-d
+        BASE64ARG=-d
     elif [[ "$IMGCAT_BASE64_VERSION" =~ GNU ]]; then
-      BASE64ARG=-di
+        BASE64ARG=-di
     else
-      BASE64ARG=-D
+        BASE64ARG=-D
     fi
     base64 $BASE64ARG
 }
@@ -53,13 +54,13 @@ function b64_decode() {
 #   filename: Filename to convey to client
 #   inline: 0 or 1
 #   base64contents: Base64-encoded contents
-#   print_filename: If non-empty, print the filename 
+#   print_filename: If non-empty, print the filename
 #                   before outputting the image
 function print_image() {
     print_osc
     printf '1337;File='
     if [[ -n "$1" ]]; then
-      printf 'name='`printf "%s" "$1" | b64_encode`";"
+        printf 'name='$(printf "%s" "$1" | b64_encode)";"
     fi
 
     printf "%s" "$3" | b64_decode | wc -c | awk '{printf "size=%d",$1}'
@@ -69,7 +70,7 @@ function print_image() {
     print_st
     printf '\n'
     if [[ -n "$4" ]]; then
-      echo $1
+        echo $1
     fi
 }
 
@@ -78,15 +79,15 @@ function error() {
 }
 
 function show_help() {
-    echo "Usage: imgcat [-p] filename ..." 1>& 2
-    echo "   or: cat filename | imgcat" 1>& 2
+    echo "Usage: imgcat [-p] filename ..." 1>&2
+    echo "   or: cat filename | imgcat" 1>&2
 }
 
 function check_dependency() {
-  if ! (builtin command -V "$1" > /dev/null 2>& 1); then
-    echo "imgcat: missing dependency: can't find $1" 1>& 2
-    exit 1
-  fi
+    if ! (builtin command -V "$1" >/dev/null 2>&1); then
+        echo "imgcat: missing dependency: can't find $1" 1>&2
+        exit 1
+    fi
 }
 
 ## Main
@@ -110,16 +111,19 @@ check_dependency wc
 # Look for command line flags.
 while [ $# -gt 0 ]; do
     case "$1" in
-    -h|--h|--help)
+    -h | --h | --help)
         show_help
         exit
         ;;
-    -p|--p|--print)
+    -p | --p | --print)
         print_filename=1
         ;;
-    -u|--u|--url)
+    -u | --u | --url)
         check_dependency curl
-        encoded_image=$(curl -s "$2" | b64_encode) || (error "No such file or url $2"; exit 2)
+        encoded_image=$(curl -s "$2" | b64_encode) || (
+            error "No such file or url $2"
+            exit 2
+        )
         has_stdin=f
         print_image "$2" 1 "$encoded_image" "$print_filename"
         set -- ${@:1:1} "-u" ${@:3}
@@ -131,11 +135,11 @@ while [ $# -gt 0 ]; do
         error "Unknown option flag: $1"
         show_help
         exit 1
-      ;;
+        ;;
     *)
-        if [ -r "$1" ] ; then
+        if [ -r "$1" ]; then
             has_stdin=f
-            print_image "$1" 1 "$(b64_encode < "$1")" "$print_filename"
+            print_image "$1" 1 "$(b64_encode <"$1")" "$print_filename"
         else
             error "imgcat: $1: No such file or directory"
             exit 2
